version: 0.2

env:
  variables:
    AWS_ACCOUNT_ID: "<aws-account-id>"
    REGION: "<aws-region>"
    ECR_URL: "${AWS_ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com"

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies..."
  pre_build:
    commands:
      - cd vote
      - pip install -r requirements.txt
      - cd ..
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region ${REGION} | docker login --username AWS --password-stdin ${ECR_URL}

  build:
    commands:
      - echo "Building the Voting App (Python)..."
      - cd vote
      - docker build -t vote .
      - docker tag vote:latest ${ECR_URL}/vote:latest
      - cd ..
      
      - echo "Building the Worker (.NET)..."
      - cd worker
      - docker build -t worker .
      - docker tag worker:latest ${ECR_URL}/worker:latest
      - cd ..
      
      - echo "Building the Node.js Results Web App..."
      - cd result
      - npm install
      - docker build -t result .
      - docker tag result:latest ${ECR_URL}/result:latest
      - cd ..

  post_build:
    commands:
      - echo "Pushing Docker images to Amazon ECR..."
      - docker push ${ECR_URL}/vote:latest
      - docker push ${ECR_URL}/worker:latest
      - docker push ${ECR_URL}/result:latest
